export var mdistrictsMaster = [
  { Id: 202, StateId: 2, Name: { English: "Chittoor", Tamil: "சித்தூர்", Telugu: "చిత్తూరు"}},
  { Id: 206, StateId: 2, Name: { English: "Kurnool", Tamil: "கர்னூல்", Telugu: "కర్నూలు"}},
  { Id: 1212, StateId: 12, Name: { English: "Devbhoomi Dwarka", Tamil: "தேவ்பூமி துவாரகா", Telugu: "దేవ్భూమి ద్వారకా"}},
  { Id: 1801, StateId: 18, Name: { English: "Alappuzha", Tamil: "ஆலப்புழை", Telugu: "అలప్పుజ"}},
  { Id: 1802, StateId: 18, Name: { English: "Ernakulam", Tamil: "எர்ணாகுளம்", Telugu: "ఎర్నాకులం"}},
  { Id: 1807, StateId: 18, Name: { English: "Kottayam", Tamil: "கோட்டயம்", Telugu: "కొట్టాయం"}},
  { Id: 1809, StateId: 18, Name: { English: "Mallapuram", Tamil: "மல்ல புரம்", Telugu: "మల్లా పురం"}},
  { Id: 1810, StateId: 18, Name: { English: "Palakkad", Tamil: "பாலக்காடு", Telugu: "పాలక్కాడ్"}},
  { Id: 1811, StateId: 18, Name: { English: "Pathanamthitta", Tamil: "பத்தனம்திட்டா", Telugu: "పతనంతిట్ట"}},
  { Id: 1812, StateId: 18, Name: { English: "Thiruvananthapuram", Tamil: "திருவனந்தபுரம்", Telugu: "తిరువంతపురం"}},
  { Id: 3102, StateId: 31, Name: { English: "Chennai", Tamil: "சென்னை", Telugu: "చెన్నై"}},
  { Id: 3104, StateId: 31, Name: { English: "Cuddalore", Tamil: "கடலூர்", Telugu: "కడలూరు"}},
  { Id: 3108, StateId: 31, Name: { English: "Kanchipuram", Tamil: "காஞ்சிபுரம்", Telugu: "కాంచీపురం"}},
  { Id: 3109, StateId: 31, Name: { English: "Kanyakumari", Tamil: "கன்னியாகுமாரி", Telugu: "కన్యాకుమారి"}},
  { Id: 3112, StateId: 31, Name: { English: "Madurai", Tamil: "மதுரை", Telugu: "మధురై"}},
  { Id: 3113, StateId: 31, Name: { English: "Nagapattinam", Tamil: "நாகப்பட்டினம்", Telugu: "నాగపట్నం"}},
  { Id: 3117, StateId: 31, Name: { English: "Pudukottai", Tamil: "புதுக்கோட்டை", Telugu: "వారిలో పుదుకోట్టై"}},
  { Id: 3118, StateId: 31, Name: { English: "Ramanathapuram", Tamil: "ராமநாதபுரம்", Telugu: "రామనాథపురం"}},
  { Id: 3120, StateId: 31, Name: { English: "Sivaganga", Tamil: "சிவகங்கை", Telugu: "శివగంగ"}},
  { Id: 3121, StateId: 31, Name: { English: "Thanjavur", Tamil: "தஞ்சாவூர்", Telugu: "తంజావూరు"}},
  { Id: 3123, StateId: 31, Name: { English: "Thoothukudi", Tamil: "தூத்துக்குடி", Telugu: "తూతుకూడి"}},
  { Id: 3124, StateId: 31, Name: { English: "Tiruchirappalli", Tamil: "திருச்சிராப்பள்ளி", Telugu: "తిరుచిరాపల్లి"}},
  { Id: 3125, StateId: 31, Name: { English: "Tirunelveli", Tamil: "திருநெல்வேலி", Telugu: "తిరునల్వేలి"}},
  { Id: 3127, StateId: 31, Name: { English: "Tiruvallur", Tamil: "திருவள்ளூர்", Telugu: "తిరువళ్ళూరు"}},
  { Id: 3128, StateId: 31, Name: { English: "Tiruvannamalai", Tamil: "திருவண்ணாமலை", Telugu: "తిరువన్నమలై"}},
  { Id: 3129, StateId: 31, Name: { English: "Thiruvarur", Tamil: "திருவாரூர்", Telugu: "తిరువరూర్"}},
  { Id: 3130, StateId: 31, Name: { English: "Vellore", Tamil: "வேலூர்", Telugu: "వెల్లూర్"}},
  { Id: 3132, StateId: 31, Name: { English: "Virudhunagar", Tamil: "விருதுநகர்", Telugu: "విరుదునగర్"}},
  { Id: 3434, StateId: 34, Name: { English: "Sitapur", Tamil: "சீதாப்புர்", Telugu: "సీతాపూర్"}},
  { Id: 3442, StateId: 34, Name: { English: "Faizabad", Tamil: "பைசாபாத்", Telugu: "ఫైజాబాద్"}},
  { Id: 3485, StateId: 34, Name: { English: "Mathura", Tamil: "மதுரா", Telugu: "మధుర"}},
  { Id: 3503, StateId: 35, Name: { English: "Chamoli", Tamil: "சாமோலி", Telugu: "చమోలి"}},
  { Id: 3511, StateId: 35, Name: { English: "Tehri Garhwal", Tamil: "தெஹ்ரி கர்வால்", Telugu: "తెహ్రీ ఘర్వాల్"}},
  { Id: 9801, StateId: 98, Name: { English: "Mustang", Tamil: "முஸ்டாங்", Telugu: "ముస్తాంగ్"}},
  { Id: 9901, StateId: 99, Name: { English: "Vinnulagam", Tamil: "வின்னுலகம்", Telugu: "పరలోకంలో "}}
]
