// export var languages = [
//   {text: 'English', value: 'en', script: 'hk'},
//   {text: 'தமிழ்', value: 'ta', script: 'tamil'},
//   {text: 'తెలుగు', value: 'te', script: 'telugu'},
// ];
export var ln_site = [
  {text: 'English', value: 'en'},
  {text: 'தமிழ்', value: 'ta'},
  {text: 'తెలుగు', value: 'te'},
];

export var ln_song_master = [
  {text: 'English', value: 'en'},
  {text: 'தமிழ்', value: 'ta'},
  {text: 'తెలుగు', value: 'te'},
  {text: 'संस्कृतम्', value: 'sa'},
];


export var ln_sanscript = [
  {text: 'English', value: 'en', script: 'hk'},
  {text: 'தமிழ்', value: 'ta', script: 'tamil'},
  {text: 'తెలుగు', value: 'te', script: 'telugu'},
  {text: 'संस्कृतम्', value: 'sa', script: 'devanagari'},
  {text: 'বাংলা', value: 'bn', script: 'bengali'},
  {text: 'ગુજરાતી', value: 'gu', script: 'gujarati'},
  {text: 'ਪੰਜਾਬੀ', value: 'pa', script: 'gurmukhi'},
  {text: 'ಕನ್ನಡ', value: 'kn', script: 'kannada'},
  {text: 'മലയാളം', value: 'ml', script: 'malayalam'},
  {text: 'ଓଡ଼ିଆ', value: 'or', script: 'oriya'},
];

// script is being used for Sanscript Transliteration github sanskrit/sanscript.js
// when new language is added, make additions to i18n.js and store.js > text_details_messages:
export var messages = {
  en: {
    $vuetify: {
      dataIterator: {
        rowsPerPageAll: 'All',
        pageText: '{0}-{1} of {2}'
      },
      dataTable: {
        rowsPerPageText: 'Rows per page'
      }
    },
    desc: {
     "t00": "Temples, Saints and Songs of Hinduism",
     "t01": "Selections",
     "t05": "Id",
     "t10": "Vaishnavism/Saivism",
     "t20": "Views",
     "t21": "Saints; Temples; Songs",
     "t22": "Songs - Temple/Saint wise",
     "t23": "Temples sung by Saints",
     "t30": "Saints",
     "t31": "Saint-Group",
     "t40": "Temples",
     "t41": "Districts",
     "t42": "States",
     "t43": "Temples sung by Saints",
     "t50": "Songs",
     "t51": "Songs-Comp",
     "t52": "Songs-Group",
     "t53": "Songs-Language",
     "t81": "Website language",
     "t82": "Song language(s)",
     "t83": "Song meaning language(s)",
     "t84": "Song explanation language(s)",
     "t85": "Close (Autoclose in 120s)",
     "t86": "Song transliteration language(s)",
     "t87": "Lyrics language",
     "t92": "Photos",
     "t93": "Audios",
     "t94": "Videos",
     "t95": "Map",
     "t97": "About",
     "t98": "Contact",
     "t99": "Home",
     "e01": "enData not selected yet. Please select atleast one item using the filter panel on the left.",
     "e02": "enOops ! No Data available for this selection !",
     "e03": "(en If audio does not play automatically, then you have to enable auto play settings in your browser)",
     "m01": "Play",
     "m02": "Stop",
     "m03": "Pause",
     "m04": "Play word/line/para",
     "m05": "Pause word/line/para",
     "m06": "Split by words",
     "m07": "Split by line",
     "m08": "No Split",
     "m09": "Repetion/Loops",
     "m10": "Word",
     "m11": "Line",
     "m12": "0.50 Very Slow",
     "m13": "0.75 Slow",
     "m14": "1 Normal",
     "m15": "Split Choice",
     "m16": "Play Back Rate",
     "m17": "Gap in Seconds between loops",
    },

  },

    ta: {
    $vuetify: {
      dataIterator: {
        rowsPerPageAll: 'taAll',
        pageText: '{0}-{1} of {2}'
      },
      dataTable: {
        rowsPerPageText: 'taRows per page'
      }
      // dataIterator: {
      //   rowsPerPageText: 'Ta Items per page:',
      //   pageText: '{0}-{1} of {2}'
      // }
    },
    desc: {
     "t00": "இந்து மத கோயில்கள், ரிஷிகள் மற்றும் தெய்வீக பாடல்கள்",
     "t01": "தேர்வுகள்",
     "t05": " எண்",
     "t10": "வகை",
     "t20": "அறிக்கை காட்சி",
     "t21": "ரிஷிகள்; கோயில்கள் ; பாடல்கள்",
     "t22": "பாடல்கள் - கோயில்கள்/ரிஷிகள் வாரியாக",
     "t23": "பாடல் பெற்ற ஸ்தலங்கள்",
     "t30": "ரிஷிகள்",
     "t31": "ரிஷிகள்-தொகுப்பு",
     "t40": "கோயில்கள்",
     "t41": "tbcமாநிலங்கள்",
     "t42": "மாநிலங்கள்",
     "t43": "பாடல் பெற்ற ஸ்தலங்கள்",
     "t50": "பாடல்கள்",
     "t51": "பாடல்கள்-துணை தொகுப்பு",
     "t52": "பாடல்கள்-தொகுப்பு",
     "t53": "taSongs-Language",
     "t81": "taWebsite language",
     "t82": "taSong language(s)",
     "t83": "taSong meaning language(s)",
     "t84": "taSong explanation language(s)",
     "t85": "taClose (Autoclose in 60s)",
     "t86": "taSong transliteration language(s)",
     "t87": "taLyrics language",
     "t92": "taPhotos",
     "t93": "taAudios",
     "t94": "taVideos",
     "t95": "taMap",
     "t97": "எங்களை பற்றி",
     "t98": "தொடர்புக்கு",
     "t99": "முகப்பு பக்கம்",
     "e01": "taData not selected yet. Please select atleast one item using the filter panel on the left.",
     "e02": "taOops ! No Data available for this selection !",
     "e03": "(ta If audio does not play automatically, then you have to enable auto play settings in your browser)",
     "m01": "taPlay",
     "m02": "taStop",
     "m03": "taPause",
     "m04": "taPlay word/line/para",
     "m05": "taPause word/line/para",
     "m06": "taSplit by words",
     "m07": "taSplit by line",
     "m08": "taNo Split",
     "m09": "taRepetion/Loops",
     "m10": "taWord",
     "m11": "taLine",
     "m12": "0.50 taVery Slow",
     "m13": "0.75 taSlow",
     "m14": "1 taNormal",
     "m15": "taSplit Choice",
     "m16": "taPlay Back Rate",
     "m17": "taGap in Seconds between loops",
    },

  },
    te: {
    $vuetify: {
      dataIterator: {
        rowsPerPageAll: 'teAll',
        pageText: '{0}-{1} of {2}'
      },
      dataTable: {
        rowsPerPageText: 'teRows per page'
      }
      // dataIterator: {
      //   rowsPerPageText: 'Te Items per page:',
      //   pageText: '{0}-{1} of {2}'
      // }
    },
    desc: {
     "t00": "హిందూ మతం దేవాలయాలు, రిషీలు మరియు దైవిక పాటలు",
     "t01": "సెలక్షన్స్",
     "t05": " సంఖ్య",
     "t10": "రకం",
     "t20": "నివేదిక వీక్షణు",
     "t21": " రిషీల; దేవాలయాల; పాటల",
     "t22": " పాటల - దేవాలయాల/రిషీల జ్ఞానం",
     "t23": " ఋషి పాడిన ఆలయాలు",
     "t30": "రిషీల",
     "t31": "రిషీల-సమూహము",
     "t40": "దేవాలయాలు",
     "t41": "రాష్ట్రాలు",
     "t42": "రాష్ట్రాలు",
     "t43": "ఋషి పాడిన ఆలయాల",
     "t50": "సాంగ్స్",
     "t51": "సాంగ్స్-ఉప గుంపు",
     "t52": "సాంగ్స్-సమూహము",
     "t53": "teSongs-Language",
     "t81": "taWebsite language",
     "t82": "taSong language(s)",
     "t83": "taSong meaning language(s)",
     "t84": "taSong explanation language(s)",
     "t85": "teClose (Autoclose in 60s)",
     "t86": "teSong transliteration language(s)",
     "t87": "teLyrics language",
     "t92": "tePhotos",
     "t93": "teAudios",
     "t94": "teVideos",
     "t95": "teMap",
     "t97": "మా గురించి",
     "t98": "సంప్రదించండి",
     "t99": "హోమ్ పేజీ",
     "e01": "teData not selected yet. Please select atleast one item using the filter panel on the left.",
     "e02": "teOops ! No Data available for this selection !",
     "e03": "(te If audio does not play automatically, then you have to enable auto play settings in your browser)",
     "m01": "tePlay",
     "m02": "teStop",
     "m03": "tePause",
     "m04": "tePlay word/line/para",
     "m05": "tePause word/line/para",
     "m06": "teSplit by words",
     "m07": "teSplit by line",
     "m08": "teNo Split",
     "m09": "teRepetion/Loops",
     "m10": "teWord",
     "m11": "teLine",
     "m12": "0.50 teVery Slow",
     "m13": "0.75 teSlow",
     "m14": "1 teNormal",
     "m15": "teSplit Choice",
     "m16": "tePlay Back Rate",
     "m17": "teGap in Seconds between loops",
    },
  },
};

export var zicons = {
     "t00": "",
     "t01": "filter",
     "t05": "",
     "t10": "fa-om",
     "t20": "fa-filter",
     // "t20": "filter_frames",
     "t21": "person place short_text",
     "t22": "short_text - place / person",
     "t23": "place person",
     "t30": "person",
     "t31": "group",
     // "t40": "place",
     "t40": "fa-gopuram",
     "t41": "fa-map-marked-alt",
     // "t41": "terrain",
     "t42": "map",
     "t43": "place group",
     "t50": "short_text",
     "t51": "book",
     "t52": "collections_bookmark",
     "t53": "language",
     "t85": "close",
     "t92": "photo",
     "t93": "mp3",
     "t94": "movie",
     "t95": "map",
     "t97": "",
     "t98": "contacts",
     "t99": "home",
}
